name: 'Setup Java'
description: 'Download OpenJDK and set up Java'

outputs:
    java-path:
        description: 'Path to the Java installation'
        value: ${{ steps.setup-java.outputs.path }}

runs:
    using: "composite"
    steps:
        -   name: download OpenJDK
            id: download-openjdk
            shell: bash
            run: |
                download_url="https://download.java.net/java/GA/jdk24.0.1/24a58e0e276943138bf3e963e6291ac2/9/GPL/openjdk-24.0.1_linux-x64_bin.tar.gz"
                echo "downloading GNU GPL Licensed OpenJDK: https://jdk.java.net/24/"
                wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

        -   name: Set up JDK
            id: setup-java
            uses: actions/setup-java@v4
            with:
                distribution: 'jdkfile'
                jdkFile: ${{ runner.temp }}/java_package.tar.gz
                java-version: '23.0.2'
                architecture: x64
